version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    groups:
      cargo-dependencies:
        patterns:
          - "*"  # Include all dependencies in one PR
        update-types:
          - "minor"
          - "patch"
