[package]
name = "proto-crate-gen"
version = "0.1.0"
authors = ["Einride"]
description = "Generate Rust crate from trees of probobuf files"
edition = "2018"

[dependencies]
clap = "2.33.3"
walkdir = "2.3.1"
tonic-build = {version = "0.3.1", default-features = false, features = ["rustfmt", "prost", "transport"] }
codegen = "0.1.3"
anyhow = "1.0.38"

# Until fix has been approved in Prost master and/or released we use a patched version of Prost to
# allow for using protoc from current environment. /Olle
[patch.crates-io]
prost-build = { git = "ssh://git@github.com/einride/prost.git", branch = "runtime_protoc" }
