[package]
name = "protocrate"
version = "0.1.0"
authors = ["Einride <open-source@einride.tech>"]
description = "Tool for generating a Rust crate from a tree of protobuf files."
categories = ["command-line-utilities", "network-programming"]
keywords = ["grpc", "protobuf"]
repository = "https://github.com/einride/protocrate-rs"
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
walkdir = "2.3.1"
tonic-build = {version = "0.5.0", default-features = false, features = ["rustfmt", "prost", "transport"] }
prost-build = "0.8.0"
codegen = "0.1.3"
anyhow = "1.0.38"
structopt = "0.3.21"

[dev-dependencies]
tempdir = "0.3.7"
