[package]
name = "proto_crate_gen"
version = "0.1.0"
authors = ["Einride"]
description = "Generate Rust crate from trees of probobuf files"
edition = "2018"

[dependencies]
clap = "2.33.0"
walkdir = "2.3.1"
tonic-build = "0.1.1"
