on: push

name: CI

jobs:
  ci:
    env:
      BIN_NAME: protocrate
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    runs-on: "${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Build
        run: cargo build --all

      - name: Test
        run: cargo test --workspace --verbose

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Check Lints
        run: cargo clippy --all -- -D warnings

      - name: Build Release Binary
        if: startsWith(github.ref, 'refs/tags/')
        run: cargo build --all --release && strip target/release/${{ env.BIN_NAME }} && mv target/release/${{ env.BIN_NAME }} target/release/${{ env.BIN_NAME }}_${{ matrix.target }}
        env:
          PROTOC: protoc
          PROTOC_INCLUDE: .

      - name: Attach Release Binaries
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/${{ env.BIN_NAME }}_${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
